Resources:
    # ECS Cluster
    ECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: python-cluster-${self:provider.stage}
            CapacityProviders:
                - FARGATE
            DefaultCapacityProviderStrategy:
                -   CapacityProvider: FARGATE
                    Weight: 1

    # Shared CloudWatch Log Group
    ECSLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: /ecs/python-tasks-${self:provider.stage}
            RetentionInDays: 7

Outputs:
    ECSClusterArn:
        Description: ARN of the ECS cluster
        Value: !Ref ECSCluster
        Export:
            Name: ${self:service}-${self:provider.stage}-cluster-arn
